### ISSUE TITLE
Integrate forked changes with main WDIO Browserstack service

### ISSUE THREAD

**Issue by esaari** [browserstack/wdio-browserstack-service#13]
Hello, 

I'm not sure why a decision was made to fork the Browserstack service from the WDIO folks. Any fixes made to the service should be done to the main upstream repository, here: https://github.com/webdriverio/webdriverio/tree/main/packages/wdio-browserstack-service

Our organization leverages Browserstack and the WDIO Browserstack service heavily. By maintaining a fork, not only will it eventually diverge from the main in terms of features, the service will also lose out on updates necessary to make it work in future Webdriver.io versions.  

Please consider deleting this fork and merging any committed work with the main WDIO Browserstack service. 

The main service has 54,000 downloads/week. This forked version has ~110.  Your user base is already using the main service and I see no reason to switch.

**Comment by Ankit098** [comment]
Hey @esaari, we have raised the relevant PRs against the `wdio-browserstack-service` repo, the changes have been approved, we'll keep this fork up until the changes are added to the npm package in the next webdriverIO release.

**Comment by Ankit098** [comment]
We have deprecated the browserstack fork of the service, changes have been released in upstream repo.
